USE FavoriteColorDb;

CREATE TABLE Person
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL DEFAULT '',
    LastName NVARCHAR(100) NOT NULL DEFAULT '',
    ZipCode NVARCHAR(20) NOT NULL DEFAULT '',
    City NVARCHAR(100) NOT NULL DEFAULT '',
    Color NVARCHAR(50) NOT NULL DEFAULT ''
);